### ISSUE TITLE
Modularize Integration Service

### ISSUE THREAD

**Issue by Hemanthr1** [Oscorp-HQ/quash-max#17]
## Issue Description
Refactor the createOrUpdateIntegration() method in the Integration Service to enhance modularity and improve code structure.

### Expected Behavior
The refactored method should be more modular, promoting better readability and maintainability of the code.

### Actual Behavior
The current implementation of createOrUpdateIntegration() is too monolithic, making it difficult to manage and extend.

**Comment by JishnuGoyal** [comment]
I would like to work on this issue, assign this to me please. @ironmark3 @Hemanthr1

**Comment by Hemanthr1** [comment]
@JishnuGoyal <https://github.com/JishnuGoyal> assigned!
