### ISSUE TITLE
 Revamp User Controller

### ISSUE THREAD

**Issue by Hemanthr1** [Oscorp-HQ/quash-max#20]
## Issue Description
Refactor the User Controller by removing the use of authentication.getAuthenticated() and implement authentication handling using try-catch blocks.

### Expected Behavior
The User Controller should robustly manage authentication errors through proper exception handling, enhancing overall stability.

### Actual Behavior
The current implementation relies on authentication.getAuthenticated(), which may not adequately handle exceptions.

**Comment by JishnuGoyal** [comment]
Hi @Hemanthr1 , I would like to work on this issue. Could you please assign this to me?

**Comment by ironmark3** [comment]
@JishnuGoyal assigned!

**Comment by JishnuGoyal** [comment]
Thanks for assigning me this @ironmark3 . I have linked a PR and waiting for a review :)
